<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

Using Python to solve scientific problems. We must hence transform, store and minipulate data to yield a solution like Lists, 
Numpy array, 
Dictionari, s
Tup, es
Datafr and mes
Classes

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

#### Python Lists

In [9]:
horse_names = ["Jessie", "Woody", "lighter"]
horse_info = ["fast horse", "middle horse", "slow horse"]

#### Numpy Arrays

In [11]:
import numpy as np
np_horse_names = np.array(["Jessie", "Woody", "lighter"])
np_pony_names = np.array(["fast horse", "middle horse", "slow horse",])

#### Dictionaries

In [12]:
horse_info = { 
    "Jessie": "fast horse", #Jessie is key, fast horse is value
    "Woody": "middle horse",
    "lighter": "slow horse"

}

- Dictionaries use a key and an associated value separated by a :
- Dictionaries easier than arrays
- 
For lists and arrays, the order matters. I.e.Jessiean’ must be in the same position asfast horserk’ for things to work.

## 1.2 Accessing data from a list (or array)

Python starts counting at 0. To access particular element in the list or array, need to specify the relevant index starting from zero. 
![Photo](https://phyweb.physics.nus.edu.sg/~chammika/sp2273/docs/python_basics/03_storing-data/python-zero-indexed-counting.png)



In [14]:
horse_names[0]

'Jessie'

In [15]:
horse_names[1]

'Woody'

Use negative index to count from the back of the list (no need to know list size)

In [17]:
horse_names[2]

'lighter'

In [18]:
horse_names[-1]

'lighter'

## 1.3 Accessing data from a dictionary

In [19]:
horse_info["Jessie"]

'fast horse'

In [20]:
horse_info["Woody"]

'middle horse'

### Access all Keys

In [21]:
horse_info.keys()

dict_keys(['Jessie', 'Woody', 'lighter'])

### Access all values

In [22]:
horse_info.values()

dict_values(['fast horse', 'middle horse', 'slow horse'])

## 1.4 Higher dimensional lists

### 2D Lists

In [26]:
two_list_horse_info = [["Jessie", "Fast Horse"],
                       ["Woody", "Middle Horse"],
                       ["lighter", "Slow Horse"]]

# 2 Lists vs. Arrays

## 2.1 Size

Use the len() function to know how many elements for lists and arrays

In [28]:
list_names = [[1, "Andy"], [2, "Bobby"], [3, "Carrie"], [4, "Daniel"]]

In [30]:
len(list_names)

4

In [29]:
array_names = np.array(list_names) #convert list to array

In [31]:
len(array_names)

4

In [33]:
array_names.shape #no bracket because shape not function but is attribute of numpy

(4, 2)

## 2.2 Arrays are fussy about type

- **Arrays only a single data type**
- lists >1 data type

In [35]:
list_letters = [1, 2, 3, "Y", "E"]
array_letters = np.array(list_letters)

In [37]:
list_letters #List retains original data type

[1, 2, 3, 'Y', 'E']

In [38]:
array_letters #Array cause numbers to be converted to english

array(['1', '2', '3', 'Y', 'E'], dtype='<U11')

## 2.3 Adding a number

**Only array can add numbers**

In [46]:
list_numbers = [2, 4, 6, 8]
array_numbers = np.array(list_numbers)

In [43]:
list_numbers + 10

TypeError: can only concatenate list (not "int") to list

In [48]:
array_numbers + 10 #array can add numbers 

array([12, 14, 16, 18])

## 2.4 Adding another list

In [52]:
list_1 = [2, 4, 6, 8, 10]
list_2 = [20, 40, 60, 80, 100]
array_1 = np.array(list_1)
array_2 = np.array(list_2)

**Adding lists causes them to grow:**

In [53]:
list_1 + list_2

[2, 4, 6, 8, 10, 20, 40, 60, 80, 100]

**Adding arrays is an mathematical operation:**

In [54]:
array_1 + array_2

array([ 22,  44,  66,  88, 110])

## 2.5 Multiplying by a Number

**list grows**

In [55]:
list_1*2

[2, 4, 6, 8, 10, 2, 4, 6, 8, 10]

**Array multipies elements by number**

In [57]:
array_1*2

array([ 4,  8, 12, 16, 20])

## 2.6 Squaring

**Cannot square lists, only can sqaure arrays**

In [59]:
list_1**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [60]:
array_1**2

array([  4,  16,  36,  64, 100])

## 2.7 Asking questions

**Lists:**

In [61]:
list_1 == 4 #Works but it is asking whether list_1 is integer 4

False

In [62]:
list_1 == [2, 4, 6, 8, 10]

True

In [64]:
list_1 > 2 #Does not work

TypeError: '>' not supported between instances of 'list' and 'int'

**Arrays:**

In [66]:
array_1 == 2 #Asking whether each element is 2

array([ True, False, False, False, False])

In [68]:
array_1 > 5 #Asking whether each element more than 5

array([False, False,  True,  True,  True])

## 2.8 Mathematics

### Sum

In [81]:
sum(list_1) #Base python function

30

In [79]:
list_1.sum() #does not work becuase sum() method not available

AttributeError: 'list' object has no attribute 'sum'

In [71]:
sum(array_1)

30

In [72]:
#or
array_1.sum()

30

### Max 

In [74]:
max(list_1) #Base python function

10

In [76]:
array_1.max()

10

### Min 

In [77]:
min(list_1) #Base python function

2

In [78]:
array_1.min()

2

### Mean

In [84]:
array_1.mean()

6.0

### Standard Deviation

In [85]:
array_1.std()

2.8284271247461903

# Exercises & Self-Assessment

An operation on a list works on the whole list. 
In contrast, an operation on an array works on the individual elements of the array.

## Footnotes