<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

Accessing and modifying lists, arrays and dictionaries and gain a better understanding of the differences and similarities between lists, NumPy arrays and dictionaries.

# 1 Subsetting: Indexing and Slicing

Subsetting means to ‘select’:
1. **Indexing** refers to selecting one element.
2. **Slicing** refers to selecting a range of elements.

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

Works for both lists and arrays: **If you slice with [i:j], the slice will start at i and end at j-1, giving you a total of j-i elements.**

| Syntax    | Result                          |                                 |
|-----------|---------------------------------|---------------------------------|
| x[0]      | First element                   | 'a1'                            |
| x[-1]     | Last element                    | 'j10'                           |
| x[0:3]    | Index 0 to 2                    | ['a1','b2','c3']                |
| x[1:6]    | Index 1 to 5                    | ['b2','c3','d4','e5','f6']      |
| x[1:6:2]  | Index 1 to 5 in steps of 2      | ['b2','d4','f6']                |
| x[5:]     | Index 5 to the end              | ['f6','g7','h8','i9','j10']     |
| x[:5]     | Index 0 to 5                    | ['a1','b2','c3','d4','e5']      |
| x[5:2:-1] | Index 5 to 3 (i.e., in reverse) | ['f6','e5','d4']                |
| x[::-1]   | Reverses the list               | ['j10','i9','h8',...,'b2','a1'] |

In [8]:
import numpy as np
name_list = ["Andy", "Benny", "Carrie", "Daniel", "Effie", "Fedrick", "Garry", "Harry"]
name_array = np.array(name_list)

print(name_list[0])
print(name_array[-1])
print(name_list[0:4])
print(name_array[1:4])
print(name_list[0:3:2])
print(name_array[3:])
print(name_list[:3])
print(name_array[6:1:-1])
print(name_list[6:1:-2])
print(name_list[6:1:1]) #Does not work
print(name_array[6:1]) #Does not work
print(name_list[::-1])

Andy
Harry
['Andy', 'Benny', 'Carrie', 'Daniel']
['Benny' 'Carrie' 'Daniel']
['Andy', 'Carrie']
['Daniel' 'Effie' 'Fedrick' 'Garry' 'Harry']
['Andy', 'Benny', 'Carrie']
['Garry' 'Fedrick' 'Effie' 'Daniel' 'Carrie']
['Garry', 'Effie', 'Carrie']
[]
[]
['Harry', 'Garry', 'Fedrick', 'Effie', 'Daniel', 'Carrie', 'Benny', 'Andy']


## 1.2 Arrays only | Subsetting by masking

Numpy Masking only allows the true subset to be seen:

In [67]:
import numpy as np
np_array = np.array([2,4,6,8,10,12,14,16,18,20])
my_mask = np_array > 10
my_mask #True is element more than 10

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [19]:
np_array[my_mask]

array([12, 14, 16, 18, 20])

Shorthand:

In [20]:
np_array[np_array > 10]

array([12, 14, 16, 18, 20])

In [23]:
np_array[~(np_array > 10)] #Invert our mask by using the ~ (Bitwise Not operator)

array([ 2,  4,  6,  8, 10])

In [28]:
np_array[(np_array>10) & (np_array<14)] # & means and

array([12])

In [30]:
np_array[(np_array>10) | (np_array<6)] # | means or

array([ 2,  4, 12, 14, 16, 18, 20])

- Bitwise Not (~)
- Bitwise And (&)
- Bitwise Or (|)

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [37]:
list_2d = [[1, "Andy"], [2, "Benny"], [3, "Carrie"], [4, "Daniel"], [5, "Effie"], [6, "Fedrick"]]
array_2d = np.array(list_2d)
#Index 3 (same syntax)
print(list_2d[3])
print(array_2d[3])

[4, 'Daniel']
['4' 'Daniel']


In [36]:
#First element of index 3 (different syntax)
print(list_2d[3][0])
print(array_2d[3,0]) #Only one square bracket

4
4


In [38]:
#Second element of index 3 (different syntax)
print(list_2d[3][1])
print(array_2d[3,1]) #Only one square bracket

Daniel
Daniel


In [35]:
#First 3 elements (same syntax)
print(list_2d[:3])
print(array_2d[:3])

[[1, 'Andy'], [2, 'Benny'], [3, 'Carrie']]
[['1' 'Andy']
 ['2' 'Benny']
 ['3' 'Carrie']]


In [40]:
#First element of first 3 sub-list
print(list_2d[:3][0]) #takes first of the list from list_2d[:3]
print(array_2d[:3,0])

[1, 'Andy']
['1' '2' '3']


In [42]:
#First element of Index 3-6
print(list_2d[3:6][0]) #takes first of the list from list_2d[3]
print(array_2d[3:6,0])

[4, 'Daniel']
['4' '5' '6']


In [45]:
print(array_2d[:,0])
print(array_2d[:,1])

['1' '2' '3' '4' '5' '6']
['Andy' 'Benny' 'Carrie' 'Daniel' 'Effie' 'Fedrick']


## 1.4 Growing lists

Arrays hard to grow, lists are easier for this

In [48]:
x = ["Horse", "Pony"]*5
print(x)

['Horse', 'Pony', 'Horse', 'Pony', 'Horse', 'Pony', 'Horse', 'Pony', 'Horse', 'Pony']


**Growing list by adding one element at a time:**

In [50]:
# Method 1:
x = ["Andy"]
x = x + ["Bobby"]
x = x + ["Carrie"]
x

['Andy', 'Bobby', 'Carrie']

In [52]:
# Method 2:
x = ["Andy"]
x += ["Bobby"]
x += ["Carrie"]
x

['Andy', 'Bobby', 'Carrie']

In [56]:
# Method 3: (runs faster)
x = ["Andy"]
x.append("Bobby") #Need to use curve bracket
x.append("Carrie")
x

['Andy', 'Bobby', 'Carrie']

**Growing lists more than one element at a time**

In [58]:
# Method 1:
x = ['Andy', 'Bobby', 'Carrie']
x += ["Daniel", "Effie"]
x

['Andy', 'Bobby', 'Carrie', 'Daniel', 'Effie']

In [59]:
# Method 2:
x = ['Andy', 'Bobby', 'Carrie']
x.extend(["Daniel", "Effie"])
x

['Andy', 'Bobby', 'Carrie', 'Daniel', 'Effie']

In [61]:
# Method 3:
x = ['Andy', 'Bobby', 'Carrie']
x.append(['Andy', 'Bobby', 'Carrie']) #Will produce list within list
x

['Andy', 'Bobby', 'Carrie', ['Andy', 'Bobby', 'Carrie']]

# Some loose ends

## 1.5 Tuples

Tuples are similar to lists but use ( ) and cannot be changed after creation (immutable)

In [64]:
tubule_names = ('Andy', 'Bobby', 'Carrie')
tubule_names[0]

'Andy'

# Exercises & Self-Assessment

## 1.6 Be VERY careful when copying lists and arrays

In [66]:
x = ['Andy', 'Bobby', 'Carrie']
y = x.copy()
z = x.copy()
print(y)
print(z)

['Andy', 'Bobby', 'Carrie']
['Andy', 'Bobby', 'Carrie']


## Footnotes